#!/bin/sh
#
# Start aa-mirror-rs daemon
#
# For documentation and command line parameters go to:
# https://github.com/manio/aa-mirror-rs

DAEMON="aa-mirror-rs"
PIDFILE="/var/run/$DAEMON.pid"
AA_MIRROR_RS_ARGS=""

RETVAL=0

case "$1" in
	start)
		printf "Starting $DAEMON: "
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/bin/$DAEMON" -- $AA_MIRROR_RS_ARGS
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $DAEMON: "
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
